name: Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: bundle install

    - name: Run Rubocop
      run: make lint
